export const GET_ALL_PACIENTE_DNI = "GET_ALL_PACIENTE_DNI";
export const POST_EVOLUCION_TEXTO_SIMPLE = "POST_EVOLUCION_TEXTO_SIMPLE";
export const POST_EVOLUCION_LABORATORIO = "POST_EVOLUCION_LABORATORIO";
export const POST_EVOLUCION_RECETA = "POST_EVOLUCION_RECETA";
export const GET_ALL_MEDICAMENTOS = "GET_ALL_MEDICAMENTOS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

