export const diagnosticos = [
    "Gripe común",
    "Resfriado común",
    "Amigdalitis",
    "Dengue",
    "Fiebre Chikungunya",
    "Zika",
    "Bronquitis aguda",
    "Neumonía leve",
    "Sinusitis aguda",
    "Faringitis viral",
    "Faringitis bacteriana",
    "Influenza estacional",
    "Varicela",
    "Conjuntivitis viral",
    "Conjuntivitis bacteriana",
    "Rinitis alérgica",
    "Dermatitis por contacto",
    "Gastroenteritis viral",
    "Tos ferina",
    "Herpes labial",
    "Laringitis aguda",
    "Mononucleosis infecciosa",
    "Fiebre tifoidea",
    "Diarrea infecciosa",
    "Escarlatina"
];
